### ISSUE TITLE
Documentation and detector metadata (locations) missing

### ISSUE THREAD

**Issue by kudaras** [vilnius/traffic#1]
While this data looks very interesting, it is unusable until there is some documentation about the detector locations and data fields

**Comment by vabalas** [comment]
Thank you for the input! We are delighted that you are checking out what we upload! This traffic rep  was intended to hand over data to Shiny app, so thus the sloppy work. Updated with what we currently have on these detectors. Will update with more detail, as soon as we have anything more.
